openapi: 3.0.0
info:
  title: prontogram
  version: '1.0'
  description: È l'API offerta dall'APP di messaggistica *Prontogram* che vi racchiude la capability di inoltrare messaggi.
servers:
  - url: 'https://soseng-unibo.stoplight.io/mocks/soseng-unibo/soseng-project-documentation/6636887'
    description: testing
paths:
  /message:
    get:
      summary: Restituisci tutti i messaggi
      tags: []
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              description: ''
              type: object
            examples:
              example-1: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: Dire che è al livello 3 di REST. Ricordarsi di aggiungere i codici di errore per quel livello.
      operationId: post-allmessage
      description: 'È la risorsa che, a fronte di una richiesta HTTP che specifica un `token` identificativo, restituisce tutti i messaggi (in blocchi di cardinalità n) cui ha accesso il fruitore (utente o ACMESky) identificato da quel token: in dettaglio, l''''utente ha accesso solo ai messaggi di cui è destinatario, mentre ACMESky ha accesso a tutti i messaggi che ha inoltrato ai suoi utenti mediante Prontogram e potrebbe richiederli per fini statistici, ad esempio.'
      security:
        - tokenSessione: []
      responses:
        '200':
          description: OK
          content:
            application/vnd.api+json:
              schema:
                description: ''
                type: object
                properties:
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        description: link al blocco corrente
                      next:
                        type: string
                        description: link al blocco successivo
                      prev:
                        type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: object
                          properties:
                            body:
                              type: string
                            receiver:
                              type: string
                            data:
                              type: string
                        links:
                          type: object
                          properties:
                            self:
                              type: string
                              description: Link al messaggio
                            next:
                              type: string
                              description: link a messaggio successivo in senso temporale
                            prev:
                              type: string
              examples:
                /message/mariorossi:
                  value:
                    links:
                      self: /message/mariorossi/from/0
                      next: /message/mariorossi/from/10
                      prev: /message/mariorossi/from/0
                    data:
                      - message:
                          body: 'nuova offerta, codice 1234'
                          receiver: mariorossi
                          date: '2020-03-02, 16:06 CET'
                        links:
                          self: /message/mariorossi/0
                          next: /message/mariorossi/1
                          prev: /message/mariorossi/0
                      - message:
                          body: 'nuova offerta, codice 1235'
                          receiver: mariorossi
                          date: '2020-03-05, 12:06 CET'
                        links:
                          self: /message/mariorossi/1
                          next: /message/mariorossi/2
                          prev: /message/mariorossi/0
                /message/mariorossi/4:
                  value:
                    links:
                      self: /message/mariorossi/4
                      next: /message/mariorossi/5
                      prev: /message/mariorossi/3
                    data:
                      - message:
                          body: 'nuova offerta, codice 1234'
                          receiver: mariorossi
                          date: '2020-03-02, 16:06 CET'
                        links:
                          self: /message/mariorossi/4
                          next: /message/mariorossi/5
                          prev: /message/mariorossi/3
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
    parameters:
      - required: true
  /createmessage:
    post:
      summary: ''
      operationId: post-createmessage
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          headers:
            Content-Type:
              schema:
                type: string
              description: application/vnd.api+json
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
      description: Crea (manda) un messaggio
      parameters: []
      security:
        - tokenSessione: []
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              description: ''
              type: object
              properties:
                data:
                  type: object
                  properties:
                    receiver:
                      type: string
                      minLength: 1
                    body:
                      type: string
                      minLength: 1
                  required:
                    - receiver
                    - body
              required:
                - data
            examples:
              Esempio di messaggio:
                value:
                  data:
                    receiver: Mario rossi
                    body: 'Nuova offerta. Inserisci codice sul sito: 1234'
        description: Formato del messaggio
  '/message/{username}':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '308':
          description: Permanent Redirect (experiemental)
          headers:
            Location:
              schema:
                type: string
              description: '/message/{username}/from/0'
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
      operationId: get-message-username
      security:
        - tokenSessione: []
  '/message/{username}/from/{messageid}':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
      - schema:
          type: string
        name: messageid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      message:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - sender
                            - body
                            - date
                          properties:
                            sender:
                              type: string
                              minLength: 1
                            body:
                              type: string
                              minLength: 1
                            date:
                              type: string
                              minLength: 1
                            links:
                              type: object
                              properties:
                                self:
                                  type: string
                                  minLength: 1
                                next:
                                  type: string
                                  minLength: 1
                                prev:
                                  type: string
                                  minLength: 1
                              required:
                                - self
                                - next
                                - prev
                    required:
                      - message
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        minLength: 1
                      next:
                        type: string
                        minLength: 1
                      prev:
                        type: string
                        minLength: 1
                    required:
                      - self
                      - next
                      - prev
                required:
                  - data
                  - links
              examples:
                example-1:
                  value:
                    data:
                      message:
                        - sender: ACMEsky
                          body: 'Nuova offerta, inserisci codice 1234'
                          date: '2021-03-04, 21:25 CET'
                          links:
                            self: /message/mariorossi/0
                            next: /message/mariorossi/1
                            prev: /message/mariorossi/0
                        - sender: ACMEsky
                          body: 'Nuova offerta, inserisci codice 4321'
                          date: '2021-03-04, 21:25 CET'
                          links:
                            self: /message/mariorossi/1
                            next: /message/mariorossi/2
                            prev: /message/mariorossi/0
                    links:
                      self: /message/mariorossi/from/0
                      next: /message/mariorossi/from/10
                      prev: /message/mariorossi/from/0
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
      operationId: get-message-username-from-messageid
      security:
        - tokenSessione: []
  '/message/{username}/{messageid}':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
      - schema:
          type: string
        name: messageid
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      sender:
                        type: string
                        minLength: 1
                      body:
                        type: string
                        minLength: 1
                      date:
                        type: string
                        minLength: 1
                    required:
                      - sender
                      - body
                      - date
                  links:
                    type: object
                    properties:
                      self:
                        type: string
                        minLength: 1
                      next:
                        type: string
                        minLength: 1
                      prev:
                        type: string
                        minLength: 1
                    required:
                      - self
                      - next
                      - prev
                  meta:
                    type: object
                    properties:
                      id:
                        type: number
                    required:
                      - id
                required:
                  - data
                  - links
                  - meta
              examples:
                example 1:
                  value:
                    data:
                      sender: ACMEsky
                      body: 'Nuova offerta, inserisci codice 1234'
                      date: '2021-03-04, 21:25 CET'
                    links:
                      self: /message/mariorossi/1
                      next: /message/mariorossi/2
                      prev: /message/mariorossi/0
                    meta:
                      id: 1234
        '400':
          description: Bad Request
        '406':
          description: Not Acceptable
        '415':
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-message-username-messageid
      security:
        - tokenSessione: []
components:
  securitySchemes:
    tokenSessione:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: Abbiamo utilizzato OAuth2 come schema di sicurezza perché consente di creare un token di sessione che permette agli utenti di essere identificati da Prontogram e di fruire dei servizi che espone.
